services:
  # The "Vault" - Permanent Database
  postgres-db:
    image: postgres:latest
    container_name: customer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # The "Whiteboard" - High-speed Cache
  redis-cache:
    image: redis:latest
    container_name: customer_redis
    ports:
      - "6379:6379"
    restart: always

# This ensures your data stays safe even if you delete the containers
volumes:
  postgres_data: